//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 10:12:10 AM CET 
//


package eu.datex.v220;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColourEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ColourEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="amber"/&gt;
 *     &lt;enumeration value="blue"/&gt;
 *     &lt;enumeration value="green"/&gt;
 *     &lt;enumeration value="red"/&gt;
 *     &lt;enumeration value="white"/&gt;
 *     &lt;enumeration value="whiteYellow"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ColourEnum")
@XmlEnum
public enum ColourEnum {

    @XmlEnumValue("amber")
    AMBER("amber"),
    @XmlEnumValue("blue")
    BLUE("blue"),
    @XmlEnumValue("green")
    GREEN("green"),
    @XmlEnumValue("red")
    RED("red"),
    @XmlEnumValue("white")
    WHITE("white"),
    @XmlEnumValue("whiteYellow")
    WHITE_YELLOW("whiteYellow");
    private final String value;

    ColourEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ColourEnum fromValue(String v) {
        for (ColourEnum c: ColourEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
