//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 10:12:10 AM CET 
//


package eu.datex.v220;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysicalMountingEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PhysicalMountingEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="centralReservationMounted"/&gt;
 *     &lt;enumeration value="gantryMounted"/&gt;
 *     &lt;enumeration value="overheadBridgeMounted"/&gt;
 *     &lt;enumeration value="roadsideCantileverMounted"/&gt;
 *     &lt;enumeration value="roadsideMounted"/&gt;
 *     &lt;enumeration value="trailerMounted"/&gt;
 *     &lt;enumeration value="tunnelEntranceMounted"/&gt;
 *     &lt;enumeration value="vehicleMounted"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PhysicalMountingEnum")
@XmlEnum
public enum PhysicalMountingEnum {

    @XmlEnumValue("centralReservationMounted")
    CENTRAL_RESERVATION_MOUNTED("centralReservationMounted"),
    @XmlEnumValue("gantryMounted")
    GANTRY_MOUNTED("gantryMounted"),
    @XmlEnumValue("overheadBridgeMounted")
    OVERHEAD_BRIDGE_MOUNTED("overheadBridgeMounted"),
    @XmlEnumValue("roadsideCantileverMounted")
    ROADSIDE_CANTILEVER_MOUNTED("roadsideCantileverMounted"),
    @XmlEnumValue("roadsideMounted")
    ROADSIDE_MOUNTED("roadsideMounted"),
    @XmlEnumValue("trailerMounted")
    TRAILER_MOUNTED("trailerMounted"),
    @XmlEnumValue("tunnelEntranceMounted")
    TUNNEL_ENTRANCE_MOUNTED("tunnelEntranceMounted"),
    @XmlEnumValue("vehicleMounted")
    VEHICLE_MOUNTED("vehicleMounted");
    private final String value;

    PhysicalMountingEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PhysicalMountingEnum fromValue(String v) {
        for (PhysicalMountingEnum c: PhysicalMountingEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
