//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.07 at 10:12:10 AM CET 
//


package eu.datex.v220;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferentTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReferentTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="boundary"/&gt;
 *     &lt;enumeration value="intersection"/&gt;
 *     &lt;enumeration value="referenceMarker"/&gt;
 *     &lt;enumeration value="landmark"/&gt;
 *     &lt;enumeration value="roadNode"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ReferentTypeEnum")
@XmlEnum
public enum ReferentTypeEnum {

    @XmlEnumValue("boundary")
    BOUNDARY("boundary"),
    @XmlEnumValue("intersection")
    INTERSECTION("intersection"),
    @XmlEnumValue("referenceMarker")
    REFERENCE_MARKER("referenceMarker"),
    @XmlEnumValue("landmark")
    LANDMARK("landmark"),
    @XmlEnumValue("roadNode")
    ROAD_NODE("roadNode");
    private final String value;

    ReferentTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReferentTypeEnum fromValue(String v) {
        for (ReferentTypeEnum c: ReferentTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
